dataset:
  basedir: cache/nerf_synthetic/drums
  far: 6
  half_res: true
  near: 2
  no_ndc: true
  testskip: 1
  type: blender
experiment:
  id: drums
  logdir: logs
  print_every: 100
  randomseed: 42
  save_every: 5000
  train_iters: 200000
  validate_every: 5000
models:
  coarse:
    hidden_size: 256
    include_input_dir: true
    include_input_xyz: true
    log_sampling_dir: true
    log_sampling_xyz: true
    num_encoding_fn_dir: 4
    num_encoding_fn_xyz: 10
    num_layers: 8
    skip_connect_every: 4
    type: FlexibleNeRFModel
    use_viewdirs: true
  fine:
    hidden_size: 256
    include_input_dir: true
    include_input_xyz: true
    log_sampling_dir: true
    log_sampling_xyz: true
    num_encoding_fn_dir: 4
    num_encoding_fn_xyz: 10
    num_layers: 8
    skip_connect_every: 4
    type: FlexibleNeRFModel
    use_viewdirs: true
nerf:
  encode_direction_fn: positional_encoding
  encode_position_fn: positional_encoding
  train:
    chunksize: 16384
    lindisp: false
    num_coarse: 64
    num_fine: 64
    num_random_rays: 1024
    perturb: true
    radiance_field_noise_std: 0.2
    white_background: true
  use_viewdirs: true
  validation:
    chunksize: 16384
    lindisp: false
    num_coarse: 64
    num_fine: 64
    perturb: false
    radiance_field_noise_std: 0.0
    white_background: true
optimizer:
  lr: 0.005
  type: Adam
scheduler:
  lr_decay: 250
  lr_decay_factor: 0.1
